# 1. 빌드 베이스 이미지 설정
FROM openjdk:17-jdk-slim as builder

# 2. 작업 디렉토리 설정
WORKDIR /springboot-app

# 3. 필요한 파일들 복사
COPY . .

# 4. 실행 권한 부여
RUN chmod +x gradlew

# 5. JAR 파일 생성
RUN ./gradlew bootJar

# 6. 실제 실행을 위한 이미지 설정
FROM openjdk:17-jdk-slim

# 7. JAR 파일 및 .env 파일 복사
COPY --from=builder /springboot-app/build/libs/*.jar app.jar
COPY .env .env

# 8. 포트 설정
EXPOSE 8080

# 9. 애플리케이션 실행
ENTRYPOINT ["java", "-jar", "/app.jar"]
