# Use the official Node.js 20 image as the base image
FROM node:20

# Set the working directory to /react-app
WORKDIR /react-app

# Copy package.json to the working directory
COPY package.json .

# Remove any existing file and Install the dependencies listed in package.json
RUN rm -rf package-lock.json node_modules && npm install

# COPY package-lock.json .
COPY . .

# Expose port 5714 for TCP traffic
EXPOSE 5714/tcp

# Set the command to run the development server
CMD ["npm", "run", "dev"]